import { useState, type FormEvent } from 'react'
import { useAuth } from '../auth'
import { auth as authApi, ApiError } from '../api'
import { T, display, label, button, input, body, SANS } from '../theme'

const MIN_PASSWORD = 10

/**
 * Forced password change. Rendered instead of the entire app — not as a
 * dismissible banner — whenever the account still carries mustChangePassword.
 *
 * That flag means the password on the account was not chosen by the person
 * using it: it was generated by an admin script, or issued during a recovery.
 * Such a password has, by definition, been written down somewhere — a terminal
 * scrollback, a text message, a support ticket — and until it is replaced,
 * every one of those places is a way into a household's calendar, shopping list
 * and bank balances. Changing it signs every other device out, which is the
 * point: whatever was pasted into that chat stops working.
 *
 * Nothing is allowed in front of this screen. Not onboarding, not the PIN offer,
 * not the paywall — a person whose credentials are known to somebody else should
 * be fixing that before they are being sold anything.
 */
export default function ChangePassword() {
  const { user, refresh, signOut } = useAuth()
  const [current, setCurrent] = useState('')
  const [next, setNext] = useState('')
  const [confirm, setConfirm] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const onSubmit = async (e: FormEvent) => {
    e.preventDefault()
    if (busy) return
    if (next !== confirm) { setError('The two new passwords do not match.'); return }
    if (next.length < MIN_PASSWORD) { setError(`Use at least ${MIN_PASSWORD} characters.`); return }
    setBusy(true); setError(null)
    try {
      await authApi.changePassword(current, next)
      // Re-read /me: mustChangePassword flipping false is what lets the router
      // move on, and the server is the only thing that can flip it.
      await refresh()
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Something went wrong.')
    } finally { setBusy(false) }
  }

  return (
    <div style={{
      minHeight: '100dvh', background: T.paper, backgroundImage: T.glow, color: T.ink, fontFamily: SANS,
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: 'max(24px, env(safe-area-inset-top)) 24px max(24px, env(safe-area-inset-bottom))',
    }}>
      <form onSubmit={onSubmit} style={{ width: '100%', maxWidth: 360 }}>
        <div style={{ marginBottom: 24 }}>
          <div style={label()}>Before anything else</div>
          <h1 style={{ ...display(28), marginTop: 8 }}>Pick a password</h1>
          <p style={{ ...body(14), color: T.inkSoft, marginTop: 10 }}>
            Hi {user?.displayName || 'there'}. You're still on a temporary password —
            one somebody else has seen. Choose your own to continue; this signs you
            out everywhere else.
          </p>
        </div>

        <label style={{ display: 'block', marginBottom: 14 }}>
          <div style={label({ marginBottom: 7 })}>Temporary password</div>
          <input style={input()} type="password" value={current}
                 onChange={(e) => setCurrent(e.target.value)} autoComplete="current-password" required />
        </label>
        <label style={{ display: 'block', marginBottom: 14 }}>
          <div style={label({ marginBottom: 7 })}>New password</div>
          <input style={input()} type="password" value={next}
                 onChange={(e) => setNext(e.target.value)} autoComplete="new-password"
                 minLength={MIN_PASSWORD} required />
          <div style={label({ marginTop: 7, letterSpacing: '0.06em' })}>
            At least {MIN_PASSWORD} characters
          </div>
        </label>
        <label style={{ display: 'block', marginBottom: 22 }}>
          <div style={label({ marginBottom: 7 })}>Confirm</div>
          <input style={input()} type="password" value={confirm}
                 onChange={(e) => setConfirm(e.target.value)} autoComplete="new-password" required />
        </label>

        {error && (
          <div role="alert" style={{
            ...label({ color: T.bad, letterSpacing: '0.06em' }),
            marginBottom: 18, paddingLeft: 10, borderLeft: `2px solid ${T.bad}`, lineHeight: 1.6,
          }}>{error}</div>
        )}

        <button type="submit" disabled={busy}
                style={{ ...button('primary'), width: '100%', opacity: busy ? 0.5 : 1 }}>
          {busy ? 'Saving…' : 'Save and continue'}
        </button>
        {/* The only other way out of this screen. Somebody who cannot remember
            the temporary password needs an exit that isn't the back button. */}
        <button type="button" onClick={() => void signOut()}
                style={{ ...button('ghost'), width: '100%', marginTop: 10, color: T.muted }}>
          Sign out
        </button>
      </form>
    </div>
  )
}
