// AUTO-GENERATED by scripts/gen-charts-index.mjs — do not edit by hand.
// Re-run: npm run charts:index
//
// Empty until `npm run charts:add` vendors the Bklit components into this
// folder. Until then every demo tab shows its own "not installed" card instead
// of taking the page down.
export {}
