// Shared ICT concept glossary — the "Most Important ICT Concepts" list
// (sourced from innercircletrader.net). Single source of truth used by BOTH:
//   • app/ict/page.tsx        — the live detection page (hover info + glossary cards)
//   • app/explore/[slug]/page.tsx — the public /explore/ict marketing page
// `live: true` means the concept is auto-detected on the live chart.

export type IctConcept = { id: string; name: string; live?: boolean; body: string; href: string };

export const ICT_CONCEPTS: IctConcept[] = [
  { id: "liquidity", name: "Liquidity", live: true, href: "https://innercircletrader.net/tutorials/liquidity-in-forex-trading/",
    body: "Resting stop-loss and pending orders. Buy-side liquidity (BSL) sits above swing highs / equal highs; sell-side liquidity (SSL) below swing lows / equal lows. Smart money sweeps these pools before reversing." },
  { id: "fvg", name: "Imbalance / Fair Value Gap (FVG)", live: true, href: "https://innercircletrader.net/tutorials/fair-value-gap-trading-strategy/",
    body: "A three-candle imbalance: a gap between candle 1 and candle 3 left by aggressive delivery. Price often returns to the FVG for fair value, where it acts as support/resistance until mitigated." },
  { id: "displacement", name: "Displacement", live: true, href: "https://innercircletrader.net/tutorials/ict-displacement-move/",
    body: "A strong, high-momentum move of large-bodied candles leaving FVGs behind. Displacement validates structure breaks and the order blocks inside the leg." },
  { id: "mss", name: "Market Structure Shift (MSS)", live: true, href: "https://innercircletrader.net/tutorials/ict-market-structure-shift/",
    body: "The initial change of direction that can lead to a reversal — a counter-trend swing break confirmed by displacement. Used as a lower-timeframe entry trigger." },
  { id: "bos", name: "Break of Structure (BOS)", live: true, href: "https://innercircletrader.net/tutorials/break-of-structure-bos/",
    body: "A clean break of the prior swing in the SAME direction as the trend — confirmation the leg is continuing." },
  { id: "choch", name: "Change of Character (CHOCH)", live: true, href: "https://innercircletrader.net/tutorials/change-of-character-choch-in-trading/",
    body: "The first break of the most recent counter-trend swing — the earliest sign the trend is reversing." },
  { id: "ob", name: "Order Block", live: true, href: "https://innercircletrader.net/tutorials/ict-order-block/",
    body: "The last opposing candle before an impulse: bullish OB = last down candle before an up move; bearish OB = last up candle before a down move. A re-entry / defense zone." },
  { id: "idm", name: "Inducement (IDM)", live: true, href: "https://innercircletrader.net/tutorials/what-is-inducement-in-forex/",
    body: "A trap level that lures FOMO retail traders in early. Price typically sweeps the inducement before delivering the real directional move." },
  { id: "bias", name: "Daily Bias", live: true, href: "https://innercircletrader.net/tutorials/ict-daily-bias-trick/",
    body: "The anticipated direction for the day. Derived here from price vs the prior-day midpoint and session displacement (draw on PDH/BSL vs PDL/SSL)." },
  { id: "pd", name: "Premium & Discount Zones", live: true, href: "https://innercircletrader.net/tutorials/ict-premium-and-discount-zone-identification/",
    body: "Fibonacci from swing high↔low. Above 0.50 = premium (sellers' zone); below 0.50 = discount (buyers' zone). Equilibrium is the 0.50 line." },
  { id: "ote", name: "Optimal Trade Entry (OTE)", live: true, href: "https://innercircletrader.net/tutorials/ict-optimal-trade-entry/",
    body: "The 62%–79% retracement band of the most recent impulse leg — where smart money typically delivers the real move after the sweep." },
  { id: "po3", name: "Power of 3 (PO3 / AMD)", live: true, href: "https://innercircletrader.net/tutorials/ict-power-of-3-po3/",
    body: "The daily delivery template: Accumulation (Asia), Manipulation (London), Distribution (New York)." },
  { id: "silver", name: "Silver Bullet", live: true, href: "https://innercircletrader.net/tutorials/ict-silver-bullet-strategy/",
    body: "A one-hour high-probability window (10:00–11:00 NY) where price delivers an FVG entry in the direction of the daily bias." },
  { id: "killzones", name: "Killzones", live: true, href: "https://innercircletrader.net/tutorials/master-ict-kill-zones/",
    body: "Time windows where institutional volume concentrates: Asian, London, NY AM and NY PM killzones. Highest-probability setups occur inside them." },
  { id: "macros", name: "ICT Macros", live: true, href: "https://innercircletrader.net/tutorials/ict-macro-time-based-strategy/",
    body: "20-minute high-conviction windows inside each killzone (e.g. 09:50 NY-AM, 13:10 NY-PM) where algorithmic delivery is most concentrated." },
  { id: "smt", name: "SMT Divergence", href: "https://innercircletrader.net/tutorials/ict-smart-money-tool-smt-divergence/",
    body: "Disagreement between two correlated instruments at a key level (one makes a higher high, the other doesn't) — confirms smart money rejecting the level. Not auto-detected: needs a 2nd correlated feed (NQ) which this page doesn't carry yet." },
  { id: "turtle", name: "Turtle Soup", live: true, href: "https://innercircletrader.net/tutorials/ict-turtle-soup-trading-strategy/",
    body: "A failure at relative equal highs/lows: price sweeps the level, fails to follow through, and reverses — a clean counter-breakout entry." },
  { id: "judas", name: "Judas Swing", live: true, href: "https://innercircletrader.net/tutorials/ict-judas-swing/",
    body: "The false move at the London open that fakes retail into the wrong direction before the real move — the manipulation phase of PO3." },
  { id: "irlerl", name: "IRL & ERL", live: true, href: "https://innercircletrader.net/tutorials/ict-internal-and-external-range-liquidity/",
    body: "Internal Range Liquidity = FVGs/order blocks inside the dealing range. External Range Liquidity = swing highs/lows outside it. Price oscillates between the two." },
  { id: "breaker", name: "Breaker Block", live: true, href: "https://innercircletrader.net/tutorials/ict-order-block/",
    body: "An order block that forms after a Break of Structure: price breaks the OB, then retests it from the other side and uses it as continuation support/resistance. The failed OB flips into a breaker." },
  { id: "ifvg", name: "Inverse / Inversion FVG (IFVG)", live: true, href: "https://innercircletrader.net/tutorials/fair-value-gap-trading-strategy/",
    body: "An FVG that price VIOLATES — closes a candle BODY through (a wick poke isn't enough). The broken gap doesn't die; it inverts into a PD array in the opposite direction. Bullish IFVG: a bearish FVG closed above → flips to support/demand. Bearish IFVG: a bullish FVG closed below → flips to resistance/supply. Strongest with a liquidity sweep into the violation, in the right premium/discount zone, and aligned with HTF bias. Entry on the RETEST (often ~50% consequent encroachment), stop beyond the zone extreme, target the next liquidity / opposing PD array. On this page a spent FVG is only kept (as an IFVG, dashed box) when its break also swept liquidity; otherwise it's removed." },
  { id: "mmxm", name: "Market Maker Models (MMXM)", live: true, href: "https://innercircletrader.net/",
    body: "The market-maker buy/sell model: a staged narrative of Smart Money Reversal (SMR), re-accumulation/distribution and the original consolidation. Stage 2 (after the reversal, with liquidity + PD arrays aligned) is cited as the highest-probability leg. Detected here via its components — the SMR shows up as a CISD / MSS after a liquidity sweep in the Models feed rather than as one labeled box." },
  { id: "model2022", name: "2022 Model / Cam's Model", live: true, href: "https://innercircletrader.net/",
    body: "A simplified high-probability template: liquidity sweep (Turtle Soup) → MSS → entry on the resulting FVG / IFVG in the direction of the break. One of the cleanest reversal/continuation recipes." },
  { id: "cisd", name: "CISD (Change in State of Delivery)", live: true, href: "https://innercircletrader.net/",
    body: "The shift that confirms a new delivery phase — price stops delivering in one direction (e.g. consecutive down closes) and the first opposing close through the prior range opens a new bullish/bearish state." },
  { id: "crt", name: "Candle Range Theory (CRT)", live: true, href: "https://innercircletrader.net/",
    body: "Range-based read of a single higher-timeframe candle: its high/low define the range, the body the equilibrium. Lower-timeframe price sweeps one extreme then delivers toward the other — a framing tool for highs/lows in the models." },
  { id: "eqhl", name: "Equal Highs / Equal Lows (EQH/EQL)", live: true, href: "https://innercircletrader.net/tutorials/liquidity-in-forex-trading/",
    body: "Relative-equal swing highs (EQH = buy-side liquidity) or lows (EQL = sell-side liquidity). These clusters are obvious stop pools that smart money engineers price toward and sweeps. Detected live as clustered liquidity (BSL/SSL ×N)." },
  { id: "htfbias", name: "HTF Bias + Draw on Liquidity", live: true, href: "https://innercircletrader.net/tutorials/ict-daily-bias-trick/",
    body: "The overarching framework: set higher-timeframe directional bias, then target the liquidity pool price is drawn toward (PDH/PDL, session H/L, EQH/EQL) using lower-timeframe FVG/OTE/MSS confluence. Often called ~80% of the edge." },
];
