// ─────────────────────────────────────────────────────────────────────────────
// What each symbol is called, for the ticker picker (symbolPicker.ts) and the
// watchlist's Add box. Before this, any ticker outside the provider's sixteen
// DESCRIPTIONS showed its bare type ("stock", "etf") where its name should be.
//
// Covers the scanner universe (data/scannerTickers.ts), which is a superset of
// the chart roster. A ticker this table does not know shows no name at all,
// rather than a guess: the copy has to be literally true. Add a line when the
// roster grows.
//
// Loaded LAZILY (cbedgeProvider.ts listSymbols / getSymbolInfo import it), so
// the table never weighs on the page chunk.
// ─────────────────────────────────────────────────────────────────────────────

export const SYMBOL_NAMES: Readonly<Record<string, string>> = {
  // indexes
  SPX: 'S&P 500 Index',
  NDX: 'Nasdaq-100 Index',
  VIX: 'CBOE Volatility Index',
  RUT: 'Russell 2000 Index',
  XSP: 'Mini-SPX Index',
  // futures
  ES: 'E-mini S&P 500 futures (front month)',
  NQ: 'E-mini Nasdaq-100 futures (front month)',
  // funds
  SPY: 'SPDR S&P 500 ETF Trust',
  QQQ: 'Invesco QQQ Trust',
  IWM: 'iShares Russell 2000 ETF',
  DIA: 'SPDR Dow Jones Industrial Average ETF',
  TLT: 'iShares 20+ Year Treasury Bond ETF',
  IEF: 'iShares 7-10 Year Treasury Bond ETF',
  HYG: 'iShares iBoxx High Yield Corporate Bond ETF',
  LQD: 'iShares iBoxx Investment Grade Corporate Bond ETF',
  GLD: 'SPDR Gold Shares',
  SLV: 'iShares Silver Trust',
  GDX: 'VanEck Gold Miners ETF',
  USO: 'United States Oil Fund',
  BNO: 'United States Brent Oil Fund',
  XLF: 'Financial Select Sector SPDR Fund',
  XLE: 'Energy Select Sector SPDR Fund',
  XLK: 'Technology Select Sector SPDR Fund',
  XLC: 'Communication Services Select Sector SPDR Fund',
  XLY: 'Consumer Discretionary Select Sector SPDR Fund',
  XLV: 'Health Care Select Sector SPDR Fund',
  SMH: 'VanEck Semiconductor ETF',
  SOXX: 'iShares Semiconductor ETF',
  SOXL: 'Direxion Daily Semiconductor Bull 3X Shares',
  SOXS: 'Direxion Daily Semiconductor Bear 3X Shares',
  TQQQ: 'ProShares UltraPro QQQ',
  SQQQ: 'ProShares UltraPro Short QQQ',
  TSLL: 'Direxion Daily TSLA Bull 2X Shares',
  VXX: 'iPath Series B S&P 500 VIX Short-Term Futures ETN',
  IBIT: 'iShares Bitcoin Trust ETF',
  ETHA: 'iShares Ethereum Trust ETF',
  ARKK: 'ARK Innovation ETF',
  IGV: 'iShares Expanded Tech-Software Sector ETF',
  FXI: 'iShares China Large-Cap ETF',
  KWEB: 'KraneShares CSI China Internet ETF',
  EEM: 'iShares MSCI Emerging Markets ETF',
  EFA: 'iShares MSCI EAFE ETF',
  EWZ: 'iShares MSCI Brazil ETF',
  EWY: 'iShares MSCI South Korea ETF',
  // single names
  AAPL: 'Apple',
  AMD: 'Advanced Micro Devices',
  AMZN: 'Amazon',
  GOOGL: 'Alphabet (Class A)',
  GOOG: 'Alphabet (Class C)',
  META: 'Meta Platforms',
  MSFT: 'Microsoft',
  NVDA: 'NVIDIA',
  TSLA: 'Tesla',
  AAL: 'American Airlines Group',
  ADBE: 'Adobe',
  AMAT: 'Applied Materials',
  ARM: 'Arm Holdings',
  ASML: 'ASML Holding',
  ASTS: 'AST SpaceMobile',
  AVGO: 'Broadcom',
  BA: 'Boeing',
  BABA: 'Alibaba Group',
  BAC: 'Bank of America',
  BB: 'BlackBerry',
  BE: 'Bloom Energy',
  BMNR: 'BitMine Immersion Technologies',
  BSX: 'Boston Scientific',
  BTDR: 'Bitdeer Technologies',
  C: 'Citigroup',
  CAT: 'Caterpillar',
  CCL: 'Carnival',
  CIFR: 'Cipher Mining',
  CLS: 'Celestica',
  CMCSA: 'Comcast',
  COIN: 'Coinbase Global',
  CORZ: 'Core Scientific',
  COST: 'Costco Wholesale',
  CRCL: 'Circle Internet Group',
  CRM: 'Salesforce',
  CRWD: 'CrowdStrike',
  CRWV: 'CoreWeave',
  CSX: 'CSX',
  CVNA: 'Carvana',
  CVS: 'CVS Health',
  CVX: 'Chevron',
  DELL: 'Dell Technologies',
  DIS: 'Walt Disney',
  DKNG: 'DraftKings',
  DVN: 'Devon Energy',
  F: 'Ford Motor',
  FCX: 'Freeport-McMoRan',
  FIG: 'Figma',
  GLW: 'Corning',
  GM: 'General Motors',
  GME: 'GameStop',
  GS: 'Goldman Sachs',
  HIMS: 'Hims & Hers Health',
  HOOD: 'Robinhood Markets',
  HPQ: 'HP Inc.',
  IBM: 'IBM',
  INTC: 'Intel',
  IONQ: 'IonQ',
  IREN: 'IREN',
  JNJ: 'Johnson & Johnson',
  JPM: 'JPMorgan Chase',
  KO: 'Coca-Cola',
  LLY: 'Eli Lilly',
  LRCX: 'Lam Research',
  LVS: 'Las Vegas Sands',
  MARA: 'MARA Holdings',
  MCD: "McDonald's",
  MMM: '3M',
  MRNA: 'Moderna',
  MRVL: 'Marvell Technology',
  MSTR: 'Strategy',
  MU: 'Micron Technology',
  NBIS: 'Nebius Group',
  NFLX: 'Netflix',
  NIO: 'NIO',
  NKE: 'Nike',
  NOK: 'Nokia',
  NOW: 'ServiceNow',
  NU: 'Nu Holdings',
  NVO: 'Novo Nordisk',
  OKLO: 'Oklo',
  ONDS: 'Ondas Holdings',
  OPEN: 'Opendoor Technologies',
  ORCL: 'Oracle',
  OWL: 'Blue Owl Capital',
  OXY: 'Occidental Petroleum',
  PATH: 'UiPath',
  PBR: 'Petrobras',
  PDD: 'PDD Holdings',
  PFE: 'Pfizer',
  PLTR: 'Palantir Technologies',
  PYPL: 'PayPal Holdings',
  QBTS: 'D-Wave Quantum',
  QCOM: 'Qualcomm',
  QUBT: 'Quantum Computing Inc.',
  QXO: 'QXO',
  RBLX: 'Roblox',
  RGTI: 'Rigetti Computing',
  RIOT: 'Riot Platforms',
  RIVN: 'Rivian Automotive',
  RKLB: 'Rocket Lab',
  RTX: 'RTX',
  SHOP: 'Shopify',
  SLS: 'SELLAS Life Sciences',
  SMCI: 'Super Micro Computer',
  SNAP: 'Snap',
  SNDK: 'Sandisk',
  SOFI: 'SoFi Technologies',
  SOUN: 'SoundHound AI',
  T: 'AT&T',
  TSM: 'Taiwan Semiconductor Manufacturing',
  TTD: 'The Trade Desk',
  UBER: 'Uber Technologies',
  UNH: 'UnitedHealth Group',
  UNP: 'Union Pacific',
  UPS: 'United Parcel Service',
  V: 'Visa',
  VZ: 'Verizon Communications',
  WBD: 'Warner Bros. Discovery',
  WEN: "Wendy's",
  WMT: 'Walmart',
  WOLF: 'Wolfspeed',
  WULF: 'TeraWulf',
  XOM: 'Exxon Mobil',
}
